### ISSUE TITLE
Addresses not showing in TB78.2.2

### ISSUE THREAD

**Issue by ranman3g** [lkosson/full-address-column#1]
Initially worked like a charm after first installation.   Restarted TB and now columns have no addresses.  Removed and re-installed and still no love.

**Comment by lkosson** [comment]
Try opening a message or moving it between folders and see if columns populate for it. Also please try removing add-on, restarting TB and then re-installing the add-on.

Do you use IMAP or POP3 server? Do you use other addons, especially "Show address only", which used to work with previous TB versions and uses same column names?

**Comment by ranman3g** [comment]
Hi, apologies for the delay. didn't see the email.  

Summary: I think this is conflict between plugins that manipulate columns.  I was using "Show In/Out" for threaded folders and apparently that conflicts with Full-Address-Column.  Disabling Show In/Out has resolved the issue with Full-Address-Column.

Detail:
I had been using "Show Address only" which got disabled.  I loaded Full-Address-column and initially it worked. I use it for parsing my junk folder mostly.  I restarted TB and it stopped working and new messages that were tagged as junk did not show their addresses.  
I then removed "Show Address only" and rebooted TB and it still didn't work.  I removed Full Address Column and rebooted TB and then re-installed it and it still did not work.   I tried using it on other folders and it did not work.

I gave up and disabled it and rebooted TB and left it disabled.

Awhile later, I enabled it and suddenly it was working again.

Just now I rebooted TB and now it isn't working again.

I tried opening a message, moving it between folders and the columns still don't populate.  

I have both IMAP and POP3 accounts but the majority are POP3.  
I use 11 other plugins: CardBook, DKIM Verifier, Box file link, dropbox file link, message preview, provider for CalDav/CardDav, QuickFilters, QuickFolders, Remove Duplicate messages, show In/Out, TBSync.

Given that "Show In/Out" also plays with columns, I decided to disable it.  And after rebooting TB,  Full Column Address started working again.

I then enabled "Show In/Out" and Full-Address-Column continued to work.  

I then rebooted TB and  Full-Address-Column stopped working.   

I then disabled "Show In/Out" and Full-Address-Column remained non-functional.

I then rebooted TB (now with Show In/Out disabled and Full-Address-Column enabled) and Full-Address-Column works. 

So it would appear that it is a conflict between plugins that occurs when TB loads.

**Comment by lkosson** [comment]
Indeed there is unexpected interaction between "Show In/Out" and "Full Address Column" add-ons. "Show In/Out", in "addHandlersToCols" function in "sio_implementation.js" replaces existing column handlers with its own "sio_columnHandler".

There is not much I can do to prevent this, apart from giving FAC columns identifiers to make them look like SIO columns, as SIO skips removing handlers from its own column.

**Comment by ranman3g** [comment]
Hi,
Well that kind of sucks. :(   Does FAC have this issue with any other add-ons that modify columns?  I don't use any others that modify columns so I don't know.   If FAC is already adding the handler in a way that plays well with others, should I be reaching out to the SIO author about this?

**Comment by lkosson** [comment]
Not really sure. Most add-ons I've seen when researching developing FAC just add new column with new handler and completely ignore other handlers, default or custom. SIO is somewhat unique, because it can inject its own content into other columns, and as far as I can tell, only way to do so is to replace preexisting handlers.

Please point SIO author to this issue, I think the add-on shouldn't hijack all custom column handlers.

**Comment by ranman3g** [comment]
I will send him a link.  In looking more closely at the SIO page, it seems SIO specifically targets "recipient" and "sender" columns.  I also realize that I probably don't need the SIO add-on at this point so I'm going to remove it.  I came to TB via Eudora and SIO enabled some emulation of the Eudora UI but I have moved on from that.  Thanks for digging into this.

**Comment by nkgm-bs** [comment]
Sorry for this late comment.
I'm the developer of the mentioned ShowInOut and fixed this problem on 17. Oct.
Günter
