### ISSUE TITLE
Custom sort function for custom columns.

### ISSUE THREAD

**Issue by AmanRathoreP** [lkosson/full-address-column#16]
I recently created a [TB addon which displays relative date/time](https://github.com/AmanRathoreP/Mozilla-Thunderbird-Date-Time-Formatter?tab=readme-ov-file#demo) but because date/time is relative TB is unable to sort it only using the string data of that particular row. Currently I'm setting [`sortable` to `False`](https://github.com/AmanRathoreP/Mozilla-Thunderbird-Date-Time-Formatter/blob/01aae9df45abf10f15bb97a02a74d57977e9c55a/src/backend/custom_column.js#L50)
I would like to add a sort function, but I don't know how to do it. Will it be possible for TB 115.10.0+ to sort via a custom sort function?

**Comment by lkosson** [comment]
Provide `sortCallback` to your `ThreadPaneColumns.addCustomColumn` call. The callback should return numeric value which will be used to order rows. For further assistance, see [Thunderbird forums](https://thunderbird.topicbox.com/groups/addons).
