### ISSUE TITLE
Add license-information to repository

### ISSUE THREAD

**Issue by hex-m** [lkosson/full-address-column#17]
The [addon page](https://addons.thunderbird.net/en-US/thunderbird/addon/full-address-column/) mentions that this project is licensed under [MIT/X11 License](https://www.opensource.org/licenses/mit-license.php). I assume this is true for all the files in this repository but it would be nice if you could make that explicit.

Thanks for this very helpful extension! <3

**Comment by lkosson** [comment]
Good point. Fixed.
