### ISSUE TITLE
Add a column for "sender domain"

### ISSUE THREAD

**Issue by str-it** [lkosson/full-address-column#18]
I have adapted the locally and added another column "sender domain" which e.g. shows "github.com" if the sender is "someone@github.com".
The feature is pretty helpful if you want to sort mails by company (i.e. domain).

I hope it's okay to send a PR.

**Comment by lkosson** [comment]
Looks fine, but please set it up so that new column is initially hidden. Otherwise it would automatically show up for all users after upgrade.

**Comment by lkosson** [comment]
Thanks, merged.

**Comment by lkosson** [comment]
Version 1.2.0 is now available on ATN
