### ISSUE TITLE
Add X-Envelope-To Column

### ISSUE THREAD

**Issue by DeeZwoo** [lkosson/full-address-column#20]
It would be really helpful to be able to show the X-Envelope-To-Header as a column for Mails received through Catchall, Bcc-Mails and other use cases.
Right now the Recipient coumn of your plugin shows for example "undisclosed-recipients;" there, is simply empty or shows another completely unknown mailadress as recipient because the real recipient is hidden through BCC. As a result i cannot determine the recipient because the mail is received through a CatchAll-Mailbox and i have to open the Source of the Mail to see the real recipient.

**Comment by lkosson** [comment]
I don't think that's possible. Custom column handler/callback receives `nsIMsgDBHdr` object, which allows access only to some selected properties and headers of the message.
