### ISSUE TITLE
Not working with Thunderbird 130

### ISSUE THREAD

**Issue by michalwoz** [lkosson/full-address-column#25]
May I ask you @lkosson to check whether this is just the matter of version number bump, or TB messed sth up with their API again?

![image](https://github.com/user-attachments/assets/ccd06d9c-4418-46cd-95dd-64923f93de35)

**Comment by lkosson** [comment]
Just a version bump this time. I have posted an update, it's queued for review and approval.

**Comment by lkosson** [comment]
Version 1.2.1 is now available.
