### ISSUE TITLE
No multiple email addresses in column 'Recipient (@)'

### ISSUE THREAD

**Issue by CS-Entw** [lkosson/full-address-column#3]
Hello!
I have a problem with multiple email addresses.
The column 'Recipient (@)' lists only the first address if 'aHeader.recipients' contains more than one email addresses.

I checked the code in '_customcol.js_' at `const recipientColumnHandler` and I solved the problem with something like that (just to give you an idea):

```javascript
getAddress(aHeader) {
  const regex = /[^<]+(?=>)/g;
  let array = [...aHeader.recipients.matchAll(regex)];
  let recipientsText = array.join(', ');
  return recipientsText; 
}
```

**Comment by lkosson** [comment]
Thanks, I have updated the addon to show all recipients instead of just first one. New version should be available in a few hours, after it gets reviewed.
