### ISSUE TITLE
customcol.js

### ISSUE THREAD

**Issue by zanzara** [lkosson/full-address-column#8]
Which Extensions do you load from here:
```javascript
const EXTENSION_NAME = "full-address-column@lukasz.kosson.net";
var extension = ExtensionParent.GlobalManager.getExtension(EXTENSION_NAME);
...
Services.scriptloader.loadSubScript(extension.getURL("customcol.js"), win.FAC);
```
`customcol.js` is somehow not part of the sources?!

(Sry, that I am asking here. But in the addons section of TB posting a question isn't possible. 
I am referring to your answer there on Nov, 20th 2020)

**Comment by lkosson** [comment]
"customcol.js" is a part of this addon and is included both in XPI package and in this repo at https://github.com/lkosson/full-address-column/blob/master/src/customcol.js

**Comment by zanzara** [comment]
Sry, I dunno whyI didn't got it yesterday. Obviously it was a little too late in the evening ;-)
(and I could swear I didn't saw it)
